### ISSUE TITLE
Repository development

### ISSUE THREAD

**Issue by berezovskyi** [ssando/crawl4neo#1]
Hello Steve,

I have a few questions regarding the future of this repository:
- do you still plan to cover the Neo4j part?
- do you still plan to cover the Spring Data part?
- do you still plan to cover the DOM normalisation?
- do you plan to evolve it into something shippable, like fetching `robots.txt` automatically (or not) via `GrabManager` to use its data in the predicate?

And yes, thank you for the great tutorial series!

Best regards,
Andrew

**Comment by ssando** [comment]
Hey Andrew,

I did continue on this project for a proposed commercial product.  Sort of left the readers high and dry.  Frankly, I didn't know if anyone was interested.  So, I guess it's valuable to finish this example out.

Some of the approaches here are not really commercially viable.  My intent is more to introduce technology in simple ways.

Stay tuned!

Steve

**Comment by berezovskyi** [comment]
Thank you very much, Steve! Will be looking forward to the new articles. You might also want to look into https://www.tinyletter.com/

**Comment by ssando** [comment]
Installment 7 is available now!
It's not a useful app, but all basics are there and ready to build on.
